### ISSUE TITLE
Q about generation_labels.npy

### ISSUE THREAD

**Issue by paul-reiners** [BBillot/SynthSeg#10]
I'm trying to run SynthSeg_training.py on my own NIFTI files.  Do I leave generation_labels.npy as is, or do I need to modify it for my own data.

[This is a question, not an issue.  If there is a discussion forum for questions like this, please let me know.]

**Comment by BBillot** [comment]
Hello Paul,
there's no dedicated forum, so I will answer here in case other people are wondering about this.

So if you want to train your SynthSeg model with your own label maps, you will have to provide your own generation labels (which is basically a list of all the label values present in your training label maps).

Please read the docstring of training.py as you might find other explanations of how to use this code. Don't hesitate to go through the provided tutorials which already clarify the usage of some parameters.

Thanks,
Benjamin
