### ISSUE TITLE
Can I use/modify this software?

### ISSUE THREAD

**Issue by arokem** [BBillot/SynthSeg#15]
I see no explicit license, but I assume that you folks put this software up here so that others can use it. Would you mind adding a license? Personally, I would be excited to see this software available under an [OSI approved open-source license](https://opensource.org/licenses), but that's your choice, of course. Thanks!

**Comment by BBillot** [comment]
Hi, thanks for the suggestion!
The part of the code that is licensed is Adrian Dalca's code (neuron, pynd, pytools), but it's true that I need to add a license for SynthSeg. I'll have to look into this carefully, because I've never licensed code before.
Anyway, thanks for the tip !

**Comment by arokem** [comment]
Great! This might be helpful: https://choosealicense.com/

**Comment by BBillot** [comment]
Hi,
thanks to your suggestion I added an apache 2.0 license, which is pretty liberal, and lets you modify the code etc.
Thanks for the suggestion, this was greatly appreciated :)
Best,
Benjamin

**Comment by arokem** [comment]
That's super. Thanks Benjamin!
