### ISSUE TITLE
Git LFS for the model file

### ISSUE THREAD

**Issue by calciver** [BBillot/SynthSeg#2]
Good Day @BBillot ,

Thank you for releasing the source code and model for SynthSeg.
I am interested to try it out, but experience difficulties getting the model SynthSeg.h5 file that you have provided.

When I perform a git lfs pull, I am told that...

```
batch_response: Git LFS is disabled for this repository
error: failed to fetch some objects from 'https://github.com/BBillot/SynthSeg.git/info/lfs'

```
A solution to this would be greatly appreciated!

Thank you very much!

**Comment by BBillot** [comment]
Dear Russ Chua,

just out of curiosity, doesn't it work if you simply clone the repo ?
I don't think I used git lfs to upload the model, so that would explain why
git lfs doesn't work.

Best regards,
Benjamin

**Comment by calciver** [comment]
Dear Benjamin,

Thanks for the swift response. Yeah it doesn't work if I simply clone the repo. 
I get the following error:
`OSError: Unable to open file (file signature not found)`
and the model size is only 8 kb.

Alternatively, could you host the weights on a file sharing site that I could do a wget from?

Thanks so much!

**Comment by BBillot** [comment]
Okay it should be fixed now.
I successfully cloned the repository and made it work (you'll see that the
model is not 8kb anymore...)
It turned out to be an upload issue, as my network is not as powerful as
the one I had at work, and it keeps playing me little tricks.

Let me know if you have any other issues,
Benjamin.

**Comment by calciver** [comment]
Thanks for updating your repo! It works now!
