### ISSUE TITLE
Not able to load pretrained model in MATLAB, showing error that network architecture is missing

### ISSUE THREAD

**Issue by bsmahesh** [BBillot/SynthSeg#20]
Hi, I tried to load model present in weights folder using MATLAB, but showing error that  network architecture is missing. Can you please let me know the network architecture for this network or  Do you have any file which is having this network architecture. Thanks..

**Comment by BBillot** [comment]
Hi,
we don't support SynthSeg on MATLAB, but I guess there's a way to port a python-coded network to matlab.

Regarding the network architecture, it is described in this paper: https://arxiv.org/pdf/2107.09559.pdf (now in Section 2.2, but soon in 3.2).

If you want more precise information you can run predict in debug mode on any scan, and put a debug bullet point at:
https://github.com/BBillot/SynthSeg/blob/1c9995e0eef4047fe1b8c439069da466e0915b38/SynthSeg/predict.py#L453
and call net.summary(200), which will print all the layers used in there.

Alternatively, I think you can also extract the architecture directly from the model (under models/SynthSeg.h5).

Hope this helps,
Benjamin
