### ISSUE TITLE
Computing SD95

### ISSUE THREAD

**Issue by paul-reiners** [BBillot/SynthSeg#21]
This isn't an issue; it's a question.

Given two labeled segmentations, given as 3D arrays of the same size, is there a simple way to compute the SD95 value from functions within the SynthSeg code base?

It looks like I could use [`evaluate.evaluation`](https://github.com/BBillot/SynthSeg/blob/1c9995e0eef4047fe1b8c439069da466e0915b38/SynthSeg/evaluate.py#L213).  But I'm not sure how to construct the numpy file needed for the `path_hausdorff_95` argument.

**Comment by BBillot** [comment]
evaluate.evaluation computes Dice scores and different distance metrics including SD95 (95th percentile of the surface distance) between all segmentations in a given folder (seg_dir) and corresponding ground truth (gt_dir). Scores will be returned for all segmentations/labels in a (n_labels, n_segmentations) matrix.
path_hausdorff_95 is simply the path where the matrix containing sd95 scores will be saved.

If you simply want to compute sd95 between two (binary) masks (given as numpy arrays) you can directly call;
https://github.com/BBillot/SynthSeg/blob/1c9995e0eef4047fe1b8c439069da466e0915b38/SynthSeg/evaluate.py#L63
