### ISSUE TITLE
L/R flipping in image augmentation

### ISSUE THREAD

**Issue by paul-reiners** [BBillot/SynthSeg#22]
Does left/right flipping of hemispheres happen by default with SynthSeg image augmentation?  This is a question, not an issue.

**Comment by BBillot** [comment]
Hi, 

yes it happens by default during training. For this reason, be careful to organise the generation label list as explained in tutorial 2.

I also want to say that right/left flipping is performed by default during testing (as a form of test time augmentation), so once again be careful with the order of labels in segmentation_labels ! (you don't need to worry about this if you are using the given model without retraining!!)
