### ISSUE TITLE
Training will fail if subjects_prob is None

### ISSUE THREAD

**Issue by hvgazula** [BBillot/SynthSeg#23]
https://github.com/BBillot/SynthSeg/blob/master/SynthSeg/brain_generator.py#L319

`self.subjects_prob` does not exist unless `self.subjects_prob = None` in the `else` condition of https://github.com/hvgazula/SynthSeg/blob/master/SynthSeg/brain_generator.py#L207

**Comment by BBillot** [comment]
Yes correct, thanks for spotting the error !
