### ISSUE TITLE
Can`t run the command python ./scripts/commands/SynthSeg_predict.py --i <image> --o <segmentation> --post <post> --resample <resample> --vol <vol>

### ISSUE THREAD

**Issue by Tixi3** [BBillot/SynthSeg#25]
Hi! Thank you for this code. However, I want to test SynthSeg on some data and I tried using the command line (from cmd): python ./scripts/commands/SynthSeg_predict.py --i <image> --o <segmentation> --post <post> --resample <resample> --vol <vol> with corresponding image and segmentation path, but it won`t work. 
What might be wrong? Or is there any other way to run all those scripts (from Console in PyCharm for example)?

**Comment by BBillot** [comment]
Hi, could you please copy/paste the error message you had ? Because it's impossible to say what's wrong without it.
Thanks !

**Comment by Tixi3** [comment]
![cmd_error](https://user-images.githubusercontent.com/90840491/153083785-e07e42b1-8b19-4f92-a121-259736808178.PNG)
Hi! There is a snap of an error. "tijan" is just the name of a user. 
Thanks!

**Comment by Tixi3** [comment]
Hi! I also tried to start SynthSeg_predict.py (from scripts\commands\) from PyCharm by giving image path and path for segmentation folder as parameters (Run >Edit Configurations > Parameters : --i D:\training_seg_01.nii\subject01_seg_extra_cerebral_lesions.nii --o D:\segmentacija), but I get this error:
![pycharm_error](https://user-images.githubusercontent.com/90840491/153089431-e048ff4b-6180-4cf2-b315-8ae756709a6a.PNG)
Thanks!

**Comment by BBillot** [comment]
IN the first case you're probably not running the code from the SynthSeg directory, so you will need an absolute path to SynthSeg_predict.py

In the second case, you're nt providing python with a python executable file but with a directory so it can't work.

Moreover, once you sort the different paths, make sure you reset the default python path to the main SynthSeg folder, and source your virtual environment.
