### ISSUE TITLE
Usage of Model or Training data

### ISSUE THREAD

**Issue by BSYMAHESH** [BBillot/SynthSeg#27]
Hi, you added Apache 2.0 license to this repository. So, can we use model or training data that are present in this repository??

**Comment by BBillot** [comment]
Yes sure, that's why it's open-source :)

Here's an explanation of what you can/cannot do with license Apache 2.0:
https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by BSYMAHESH** [comment]
Thanks for your quick reply but in someone's query, you mentioned that training data is strictly private and owned by the Massachusetts General Hospital, so you won't be able to download it. Here is link to that issue
https://github.com/BBillot/SynthSeg/issues/8

So, training data present in this repository have a permission to use it??

Thanks,

**Comment by BBillot** [comment]
Sorry, the data distributed here (automated label maps) are not private, but the original images/segmentations (which was the question in #8) are.
So feel free to use, that's why there are here :)
