### ISSUE TITLE
difference with freesurfer installation

### ISSUE THREAD

**Issue by romainVala** [BBillot/SynthSeg#29]
Hello Benjamin

thanks for sharing this great works !

I install freesurfer dev version and I could run the command mri_synthseg with the -robust option (nice improvment by the way)

But I would prefer running it from this github repo 
but I can not find this option in this repository ... in SynthSeg/scripts/commands/ neither predict nor SynthSeg_predict have the -robust option

Thanks

**Comment by BBillot** [comment]
Hello,
yes sorry I haven't had time to add this bit to the github repo, so it's normal if you cannot use it yet ;)
the code still needs a bit of cleaning, so I'm likely to release the new training/testing code all at the same time.
I'll keep you posted when I do !
Benjamin

**Comment by BBillot** [comment]
Done !
Sorry, it took me a little while because I was working on my thesis.
Anyway the new testing code is out now, let me know if there's anything wrong with it :)

I still need to clean a bit the training code, so I should upload it around September 2022.

**Comment by BBillot** [comment]
Hi,
I've added all the training code for synthseg with the --robust flag. There's a brief script that tells you how this new architecture has been trained (it's in scripts/tutorials/7-synthseg+.py).

See the paper here for more details:
https://link.springer.com/chapter/10.1007/978-3-031-16443-9_52

**Comment by romainVala** [comment]
Hello
that's funny I just saw the new version of your paper yesterday ! .
Very nice work ! (i like very much the QC part you added)
