### ISSUE TITLE
Input dimensions?

### ISSUE THREAD

**Issue by MrBurnst** [BBillot/SynthSeg#3]
Hi! I can't get this to run. I tried on my data and got 
```
lab2im/edit_volumes.py", line 369, in align_volume_to_ref
    ras_axes_flo[swapped_axis_idx], ras_axes_flo[i] = ras_axes_flo[i], ras_axes_flo[swapped_axis_idx]
ValueError: setting an array element with a sequence.
```
and then I tried on the training segmentation SynthSeg_predict.py data/training_label_maps/subject01_seg.nii.gz just to check if my image dimensions are the problem, and that gave
```
merge.py", line 362, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 256, 64, 64, 96), (None, 192, 64, 64, 1920)]
```

? any ideas ?

**Comment by BBillot** [comment]
hi,
sorry for the late answer, I've just seen this.
I reformatted the code quite a bit since august. Maybe you can give it another try ?
I'm closing this issue for now, but I'm happy to reopen it if something is still not working.
Best,
Benjamin
