### ISSUE TITLE
What are the units of the Hausdorff distance as calculated in evaluate.py?

### ISSUE THREAD

**Issue by paul-reiners** [BBillot/SynthSeg#31]
What are the units of the Hausdorff distance as calculated in [evaluate.py](https://github.com/BBillot/SynthSeg/blob/cd597b080eb11bdd54e4e75b28b79b41b322c0c8/SynthSeg/evaluate.py#L63)?  Voxels?

**Comment by BBillot** [comment]
yes, exactly, it's in voxels! :)
