### ISSUE TITLE
Installation issues.

### ISSUE THREAD

**Issue by limacora45** [BBillot/SynthSeg#34]
Hi, 

I can't seem to install Synthseg by using
pip install -r requirements.txt

tried to create virtual envs with 3.6,3.7,3.8,3.9,3.10 for installation, but none worked. 

It would be really kind of you if you could provide a workable instruction for installing Synthseg by specifying version requirements, etc in details?. Your help here would be much appreciated.

**Comment by Heisenberg34** [comment]
Hi, 

Sorry my bad, I see that all the instructions are provided, since I am using Ubuntu 22.04, python 3.6 was not installing properly. After I got that to work, I could install SynthSeg 2. 

Thank you.

**Comment by limacora45** [comment]
Hi,

Sorry my bad, I see that all the instructions are provided, since I am using Ubuntu 22.04, python 3.6 was not installing properly. After I got that to work, I could install SynthSeg 2.

Thank you.
