### ISSUE TITLE
Is there any PyTorch implementation?

### ISSUE THREAD

**Issue by LightersWang** [BBillot/SynthSeg#35]
Hi,

I've read your works about SynthSeg and really like them. I have a few ideas and want to check if they are working. 
SynthSeg is implemented with TensorFlow and Keras, however, my mostly used deep learning framework is PyTorch, so it's hard for people like me to develop our own algorithms based on your repo. 
I wonder if there is any PyTorch implementation for SynthSeg? If not, I believe I'll reproduce it in PyTorch.

Thanks

**Comment by BBillot** [comment]
Hi,
sorry for the late answer.
No, unfortunately there is no pytorch version yet. But there are already some people that started working on this problem. See for example the TorchIO repo, where some augmentations (including sampling images from segmentations) are already available in pytorch.

https://github.com/fepegar/torchio/tree/main/src/torchio/transforms/augmentation

Hope this helps

**Comment by LightersWang** [comment]
Hi,

I'm not that familiar with TorchIO (mostly use MONAI developed by Nvidia), but I'll check the codes in this URL. 

Thanks for your reply!
