### ISSUE TITLE
request: docker container

### ISSUE THREAD

**Issue by jordandekraker** [BBillot/SynthSeg#36]
Would be great to have v2.0 available in a docker or singularity container. Currently I could only find [this](https://hub.docker.com/r/vanandrew/synthseg) from over a year ago.

**Comment by BBillot** [comment]
Hi,
sorry for the very late answer.
I'm not too sure about adding a dockerfile in this repo, but feel free to have a look at the suggestion by HippocampusGirl (great name btw ;)).

Closing this for now.
