### ISSUE TITLE
Dependency "pkg-resources==0.0.0" in requirements.txt breaks install in Docker/virtualenv

### ISSUE THREAD

**Issue by LeHenschel** [BBillot/SynthSeg#4]
Hey,

thanks for sharing your work. I really liked your presentation at MIDL!

I just wanted to point out, that your requirements.txt file includes the pkg-resources==0.0.0 dependency (https://github.com/BBillot/SynthSeg/blob/master/requirements.txt#L38) which unfortunately breaks the install in a fresh environment or Docker file with the following error:

> 
> Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 5)) (from versions: )
> No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 38))

The package is actually only included with pip freeze due to a bug in ubuntu which is still not fixed (https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1635463)

Removing it from the requirements file fixes the install problem.

Best,
Leonie

**Comment by BBillot** [comment]
Hello Leonie,

I'm glad you liked the presentation!
And thanks for the advice, I have removed the faulty requirement.

Best,
Benjamin
