### ISSUE TITLE
failed to predict on GPU

### ISSUE THREAD

**Issue by SpencerXia** [BBillot/SynthSeg#41]
Does anyone face the same issue？ It works well on CPU, but stuck when use GPU

**Comment by mafortin** [comment]
I tested the CPU and GPU 'versions' and both worked properly. I have been using the GPU only since that test although.

**Comment by BBillot** [comment]
Hi, sorry I've just seen this. 
How does it fail exactly ? Does it print out an error or does it just give rubbish ?
