### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by samr96** [BBillot/SynthSeg#42]
Hello, 

This is to notify you of some broken links I came across trying to insall SynthSeg. Unless I am missing something? 

1) the UCL Dropbox link to download pretrained models: https://liveuclac-my.sharepoint.com/:f:/g/personal/rmappmb_ucl_ac_uk/EtlNnulBSUtAvOP6S99KcAIBYzze7jTPsmFk2_iHqKDjEw?e=rBP0RO
2) the link to your Matlab wrapper: https://surfer.nmr.mgh.harvard.edu/fswiki/SynthSeg?action=AttachFile&do=get&target=SynthSegMatlab.zip%7CSynthSegMatlab.zip 

Screenshots below. Thanks!

![image](https://user-images.githubusercontent.com/56116775/197747627-168b2560-65ec-4bb4-9856-d14940b8a37c.png)

![image](https://user-images.githubusercontent.com/56116775/197747372-a018ec5e-4852-49ca-81d7-e96f6d4f4692.png)

**Comment by BBillot** [comment]
Hi, thanks for letting me know. 
Both links have been fixed.
Sorry for the delay. 
Thanks !

**Comment by samr96** [comment]
Great, thanks a lot!
