### ISSUE TITLE
"path_segmentation_labels_s1" isn't used in function "training_s1"

### ISSUE THREAD

**Issue by TakJim** [BBillot/SynthSeg#44]
Thank you for sharing the fantastic code! 

I think that the "path_segmentation_labels_s1" would be used in function "training_s1" though it has None. 
`segmentation_labels=None`

https://github.com/BBillot/SynthSeg/blob/09d5e7e76308d3b691861fdbf1d686e48dfea522/scripts/tutorials/7-synthseg%2B.py#L41-L57

While the function "training_s2" seems to use "path_segmentation_labels_s2"
`segmentation_labels=path_segmentation_labels_s2`
https://github.com/BBillot/SynthSeg/blob/09d5e7e76308d3b691861fdbf1d686e48dfea522/scripts/tutorials/7-synthseg%2B.py#L120-L132

**Comment by BBillot** [comment]
Good catch ! It should indeed be `segmentation_labels= path_segmentation_labels_s1` on line 49. This has now been fixed.
Thanks
