### ISSUE TITLE
Q about brain_generator constructor prior_means variable when prior_distributions='uniform'

### ISSUE THREAD

**Issue by paul-reiners** [BBillot/SynthSeg#48]
This is a question, not an "issue".

When the `brain_generator` constructor is called with `prior_distributions='uniform'`, the documentation says the  `prior_means` variable can be set to:

> a sequence of length 2, directly defining the two hyperparameters: [min, max] if prior_distributions is uniform

Don't a min and max need to be defined for each of the K classes?

**Comment by BBillot** [comment]
Not necessarily, if all the K classes have the same min and max, then you can just specify those two values as a list to prior_means.
