### ISSUE TITLE
SynthSeg: Segmentation of brain MRI scans of any contrast and resolution without retraining

### ISSUE THREAD

**Issue by zzzyzh** [BBillot/SynthSeg#50]
Hi professor,
I would like to ask if the open source code for your new paper _SynthSeg: Segmentation of brain MRI scans of any contrast and resolution without retraining_ has been updated in this repository.

**Comment by BBillot** [comment]
Hi,
yes the code is regularly updated :)
Also, I'm not a professor (maybe one day....) ;)
