### ISSUE TITLE
Matlab input folder name can't be too short

### ISSUE THREAD

**Issue by zacheidex** [BBillot/SynthSeg#51]
First off, great idea! I'm using this to generate brain masks for ADC maps. 

The issue comes from line 39 in SynthSeg.m:
if strcmp(input(end-3:end), '.nii')>0 || strcmp(input(end-6:end), '.nii.gz')>0

My folder is named 'T1w', so I got this error: Array indices must be positive integers or logical values.

Changing the folder name to 'T1_weighted' solved the issue.

Also, the output is saving as .nii.nii. Probably another easy fix there.

**Comment by BBillot** [comment]
Hi!
Thanks for the interest and for the feedback :)
I've modified the Matlab script, so hopefully you won't have the same problems as before.
Let me know if your issue hasn't been fixed.
Best
Benjamin

**Comment by BBillot** [comment]
Also, I've just re-uploaded a new version that suppresses all the unnecessary warnings related to the network architecture.

**Comment by zacheidex** [comment]
Awesome! It works as intended now. Thank you for the quick update.
