### ISSUE TITLE
How to split the specified areas?

### ISSUE THREAD

**Issue by Kimmm-pzl** [BBillot/SynthSeg#59]
Hi

How do I split the specified area, instead of splitting all the areas at once. For example, only split on 'right putamen' and 'left putamen'.
Thank you for your reply!

Best
Kim

**Comment by Kimmm-pzl** [comment]
Hi,

Thanks for your quick and clear reply! Your answer helped me a lot.

In addition, I also want to ask whether the pixel value matches the labels in the "labels table.txt" after getting the divided ".nii file", so that the structure name can be determined according to the pixel value of the ".nii file"? In other words, how do I determine what structures the different regions after segmentation represent? 

Thanks again and look forward to your reply!

Best 
Kim

**Comment by BBillot** [comment]
Yes exactly, the list of labels in labels_table.txt gives you the correspondence between the values in the output segmentation and the name of the regions.

For example, if the value of a given pixel in the segmentation in 17, the table indicates that this corresponds to left hippocampus.

PS: the label table actually follows the same labeling scheme as FreeSurfer.

**Comment by Kimmm-pzl** [comment]
Thanks for your answer, it helps me a lot!
