### ISSUE TITLE
Non-sequential label

### ISSUE THREAD

**Issue by Kimmm-pzl** [BBillot/SynthSeg#61]
Hello, can I change the label value of the SynthSeg segmentation result? For example, from the original {0,2,3,4,5,7,8...58,60} to the continuous {0,1,2,3...30,31}.

Best
Kim

**Comment by BBillot** [comment]
Yes sure!

for that you can replace 
    `seg_patch = labels_segmentation[post_patch_seg.argmax(-1).astype('int32')].astype('int32')`
by
    `seg_patch = post_patch_seg.argmax(-1).astype('int32')`
in [line 721 in predict_synthseg.py](https://github.com/BBillot/SynthSeg/blob/0369118b9a0dbd410b35d1abde2529f0f46f9341/SynthSeg/predict_synthseg.py#LL721C10-L721C10) .

Otherwise, you can also directly modify the output segmentation themselves.

**Comment by Kimmm-pzl** [comment]
Thanks for your quick and clear reply! It helps me a lot!
