### ISSUE TITLE
Training with Label maps of different size and resolution

### ISSUE THREAD

**Issue by Satob95** [BBillot/SynthSeg#64]
Hello Dr. Billot,

how is it possible to train SynthSeg with Feature Label Maps of different spatial resolutions? E.g. some of my Training data is 256x256x256, while others are 160x256x256. I understand that probably there needs to be some padding or cropping involved, but I do not have the understanding of the file formats to do so. Is there maybe some easy fix and if so, hox exactly could it be implemented?
Also: is there any way to resample Feature Label maps? E.g. take Synthsegs output at 1mm^3 and convert it into a segmentation of 0.1mm1^3 that "looks" the same and can then further be used for more detailed manual segmentation?
Thank you very much!

**Comment by BBillot** [comment]
You can have a look at the following functions:

https://github.com/BBillot/SynthSeg/blob/0369118b9a0dbd410b35d1abde2529f0f46f9341/ext/lab2im/edit_volumes.py#L424

https://github.com/BBillot/SynthSeg/blob/0369118b9a0dbd410b35d1abde2529f0f46f9341/ext/lab2im/edit_volumes.py#L1208
