### ISSUE TITLE
Transferable to non MRI modalities?

### ISSUE THREAD

**Issue by bartmch** [BBillot/SynthSeg#7]
Hi, bit of a research question. What's your experience/thought on applying this gmm generative models to other modalities such as CT scans? Thanks!

**Comment by BBillot** [comment]
Hello bartmch,
and thank you for your question.

We have recently started to conduct experiments on other types of images, such as 3d volumes reconstructed from dissection photographs. The results were promising, and we believe that we can extend our framework to new modalities.
However, we haven't tested SynthSeg (or retrained a PV-SynthSeg type of model) for CT scans yet.

Another point, somehow related to your question, is that we have recently submitted a paper (currently being reviewed), where we show that SynthSeg can successfully be applied in the context of pathologies that severely affect the brain anatomy (i.e. more than AD for instance). Specifically, we applied SynthSeg to joint segmentation of multiple sclerosis lesions and brain anatomy in brain MRI scans, showing that we perform similarly to the state-of-the-art in contrast-adaptive Bayesian segmentation*, while running two orders of magnitude faster.

Best,
Benjamin

* A contrast-adaptive method for simultaneous whole-brain and lesion segmentation in multiple sclerosis, Cerri et al., NeuroImage 2021
