### ISSUE TITLE
Run inference directly on the original NIFTI image

### ISSUE THREAD

**Issue by dongdongtong** [BBillot/SynthSeg#71]
Hello, very appreciate for your excellent work, here I got one simple question.

I have a set of SWI NIFTI images and I want to use this great work to do brain segmentation. But the spacing of images in hand (i.e., the resoluton) is not isotropic 1mm, I read your ReadME file carefully and run inference based on the instructions. I know the reason why the shape of output segmentation is different from the original image because of the resample operation.

Now I want to resample the 1mm isotropic segmentation back to the original image space based on your resample utils. But I found the resampled segmentation is a little bit shape mismatch with the original image. And I know it is very reasonable because of the calculation precision.

So could I use the inference directly on the original image? Could you please provide some suggestions? Thx~

**Comment by dongdongtong** [comment]
Or could I just comment the code of this resample block in the preprocess :)
https://github.com/BBillot/SynthSeg/blob/b4ac8561dfde091d0dca328cf79933e740d618df/SynthSeg/predict_synthseg.py#L448

**Comment by BBillot** [comment]
Hi, thanks for the interest in our work.

The network has trained on images resampled at 1mm isotropic, so I'm not sure about the results if you segment at other resolutions. I mean of course you can try, but I'm not sure about the results.

And yes, I believe you're right, if you want to disable the resampling, you only need to comment out the block you mentioned.

Let me know how it goes, I'm curious to know :)
