### ISSUE TITLE
Synthesize image for different anantomical templates

### ISSUE THREAD

**Issue by Tianyangg** [BBillot/SynthSeg#73]
Hi BBillot,

Thank you for presenting this innovative and inspiring work.

I have with a question regarding synthsizing image for a different anatomical template.

So the current sythesize/generative model (as far as i understand), make use of anatomical segmention maps (such as GM WM CSF...) for a real image, and sythesize new images based on the segementation with some combination of transformation (rigid, affine, deformation field....).

Now during my project, I'm trying to synthesize image for a new anatomical template to segment Lobes of the brain (frontal, parietal, temporal...). I've uploaded an image to illustrate the new template. These ROIs is not defined using GM/WM/CSF these tissues with similar intensity distrubitions. 

So what I'm thinking is to synthesize image with a segmentation map with GM/WM/CSF boundaries, just like you did in the paper, and then apply the same transformation to transform the new template into the synthesize image space. Is this feasible with the current code in the repository?

thanks XD

![image](https://github.com/BBillot/SynthSeg/assets/39927555/1f5b1cc9-23e7-44a4-83f0-a5aa66d77aa6)

**Comment by BBillot** [comment]
Hi, thanks for the interest in our work!

What you propose sound pretty interesting and make a lot of sense.

Despite not being directly implemented, I think you can pretty easily code your method within the SynthSeg framework. Just add another input to the generative model (your new segmentation maps), and apply the same spatial deformation as the GM/WM/CSF segmentation you use to create the images.

So yeah, I'd say it's relatively esy to implement :)

**Comment by Tianyangg** [comment]
Yes that make sense, will try it out.
Thanks for your reply XD
