### ISSUE TITLE
random segmentation failures 

### ISSUE THREAD

**Issue by ZiyaoShang** [BBillot/SynthSeg#75]
Dear author, 

When training synthseg, I observed a problem:
I loaded the models saved in each epoch during the training and applied them to the same dataset. It appears that for some (random) epochs, their saved models do not work on (a random) part of the MRI images in my dataset, producing segmentations like this. 
<img width="302" alt="Screenshot 2023-12-04 at 21 10 53" src="https://github.com/BBillot/SynthSeg/assets/46566194/390361f5-e8ab-4e02-93e8-737033740686">

The models from other epochs worked fine. 

Also, for the times when the segmentations did not work, I get( [RuntimeWarning: invalid value encountered in divide:   post_patch /= np.sum(post_patch, axis=-1)[..., np.newaxis] ) at location: SynthSeg/predict.py:528. 

Any information on this issue is greatly appreciated. Thanks a lot!

**Comment by BBillot** [comment]
hmm did you obsreve any specific pattern for the loss at those specific epochs ? It looks like your model is pretty unstable to train for some reason. when you hav the runtime error, is it caused by a division by zero, or it there a nan somewhere ? 
In any case, this is not normal behaviour, and it sounds like you need to do a bit of exploring here :)

**Comment by ZiyaoShang** [comment]
Thanks for the reply! It appears that the error itself is caused by a division by zero, which would cease to take place when disabling keep_biggest_component during inference. Also, there are no NaNs inside the raw network output. 

However, this doesn't solve the problem. After setting keep_biggest_component to False, the resulting segmentation will look like this, with the correct segmentation coexisting with the random structure that shouldn't exist. 

<img width="756" alt="image" src="https://github.com/BBillot/SynthSeg/assets/46566194/08e1a4c8-5aa4-485b-bab2-c263273b9684">

**Comment by ZiyaoShang** [comment]
Upon further examination, I found that this problem seems to be related to too many background voxels in the testing input (the problem no longer appeared after removing most of the background in the images before feeding them into the network). I will update here If there are any new related findings.
