### ISSUE TITLE
FreeSurfer dataset

### ISSUE THREAD

**Issue by efirdc** [BBillot/SynthSeg#8]
Hello,

The paper mentions a dataset with 39 T1 images with manual segmentations. FreeSurfer is cited as the source for the data, but I haven't been able to figure out where exactly to obtain it. I thought they might be somewhere in the 10GB FreeSurfer installation, and I have found a few T1 images in there but no matching segmentation maps.

Any tips on where to find this dataset?

Thanks,
Cory

**Comment by BBillot** [comment]
Hi Cory, sorry for the late answer.
Unfortunately this dataset is strictly private and owned by the Massachusetts General Hospital, so you won't be able to download it.
Benjamin
