### ISSUE TITLE
synthseg-robust 2.0

### ISSUE THREAD

**Issue by elebot4** [BBillot/SynthSeg#84]
Hi, 
thanks for your work, 
I'd like to use the SynthSeg 2.0 robust model, but I can't see it on the github repos. Could you point out where is the model? I'm also wondering where could I get access to the three different model described in the SynthSeg+ paper (segmenter1 & 2 and denoiser) and if I can use the code available here to perform the cortical parcellation? 
once again thanks a lot for your work, 
Edern

**Comment by BBillot** [comment]
Hi, thanks for the interest in our work.
As described in the installation section, ALL models are available on a UCL dropbox (link provided).
Once you completed all the steps in the installation section, you should be able to use this code, including for cortical parcellation. See how to use the code in the "Try it in one command" section.
Best
Benjamin
