### ISSUE TITLE
2.0 models missing from models directory

### ISSUE THREAD

**Issue by hvgazula** [BBillot/SynthSeg#91]
Hi @BBillot 

Could you please provide all relevant 2.0 models (I only see 1.0 version) in the `models` directory or were they intentionally not included (because of size constraints)?

https://github.com/BBillot/SynthSeg/blob/2a2aa3bbfccb83f8253a51ca8b329b9938a2646d/scripts/commands/SynthSeg_predict.py#L84-L89

**Comment by hvgazula** [comment]
Provided in a dropbox link (in README.md)

**Comment by othmane42** [comment]
The provided dropbox link (https://liveuclac-my.sharepoint.com/:f:/g/personal/rmappmb_ucl_ac_uk/EtlNnulBSUtAvOP6S99KcAIBYzze7jTPsmFk2_iHqKDjEw?e=rBP0RO) doesn't work anymore. @BBillot is it possible to update the link, please? thanks! 

<img width="169" height="57" alt="Image" src="https://github.com/user-attachments/assets/c2aadb0f-0ccf-4632-8b59-bf4ed2237367" />
