### ISSUE TITLE
[question] how to specify the GPU which should be used?

### ISSUE THREAD

**Issue by neuronflow** [BBillot/SynthSeg#95]
.

**Comment by neuronflow** [comment]
currently I do it like this:
```
CUDA_VISIBLE_DEVICES=1 python ./scripts/commands/SynthSeg_predict.py ...
```

**Comment by BBillot** [comment]
Hi, the current training function doesn't support GPU assignation, but I'm sure there are plenty of tutorials out there to explain how to do this!
